version: "3.11"

services:
  api:
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    volumes:
      - .:/code
    env_file:
      - .envs/.local/.django
    ports:
      - "8000:8000"
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
  celery:
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    command: celery worker --app=config --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .envs/.local/.django
    depends_on:
      - api
      - redis

