version: "3.11"

services:
  api: &api
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    volumes:
      - .:/code
    env_file:
      - .envs/.local/.django
    ports:
      - "8000:8000"
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
  worker:
    <<: *api
    command: celery --app=config worker --loglevel=info
    links:
      - redis
    ports: []
    depends_on:
      - api
      - redis
  beat:
    <<: *api
    command: celery --app=config beat --loglevel=info
    ports: []
    depends_on:
      - api
      - redis

