version: "3.11"

services:
  api: &api
    container_name: api
    build:
      context: .
      dockerfile: compose/prod/django/Dockerfile
    volumes:
      - .:/code
      - staticfiles:/code/static/
    env_file:
      - .envs/.prod/.django
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: sh -c "python manage.py collectstatic --no-input &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn --workers=4 --reload --max-requests=1000 config.wsgi:application -b 0.0.0.0:8000"
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
  worker:
    <<: *api
    command: celery --app=config worker --loglevel=info
    links:
      - redis
    ports: [ ]
    depends_on:
      - api
      - redis
  beat:
    <<: *api
    command: celery --app=config beat --loglevel=info
    ports: [ ]
    depends_on:
      - api
      - redis
  nginx:
    container_name: nginx
    working_dir: /code
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/prod/:/etc/nginx/conf.d:ro
      - staticfiles:/code/static/
    links:
      - web
    depends_on:
      - web


volumes:
  staticfiles: