version: "3.11"

services:
  web:
    container_name: django
    build:
      context: .
      dockerfile: compose/prod/django/Dockerfile
    volumes:
      - .:/code
      - staticfiles:/code/static/
    env_file:
      - .envs/.prod/.django
      - .envs/.prod/.postgres
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: sh -c "python manage.py collectstatic --no-input &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn --workers=4 --reload --max-requests=1000 config.wsgi:application -b 0.0.0.0:8000"

  db:
    image: postgres:13.0-alpine
    ports:
      - "30333:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .envs/.prod/.postgres

  nginx:
    container_name: nginx
    working_dir: /code
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/prod/:/etc/nginx/conf.d:ro
      - staticfiles:/code/static/
    links:
      - web
    depends_on:
      - web


volumes:
  postgres_data: {}
  staticfiles: