# Generated by Django 4.2.4 on 2023-09-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Converter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_currency", models.CharField(max_length=6)),
                ("to_currency", models.CharField(max_length=6)),
                ("amount", models.FloatField(max_length=10)),
                ("converted_amount", models.FloatField(max_length=10)),
            ],
        ),
    ]
